# Generated by Django 2.0.3 on 2018-03-28 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('securers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('securers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Secure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('secure_date', models.DateTimeField(verbose_name='date secured')),
                ('securers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('seeders', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='secure',
            name='seed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_se', to='cmct.Seed'),
        ),
        migrations.AddField(
            model_name='assign',
            name='seed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_as', to='cmct.Seed'),
        ),
        migrations.AddField(
            model_name='accept',
            name='seed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_ac', to='cmct.Seed'),
        ),
    ]
