# Generated by Django 2.0.3 on 2018-03-28 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Name of Forum')),
                ('sync_status', models.CharField(default='ready', max_length=100)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_forum', models.IntegerField(default=0)),
                ('max_cap', models.IntegerField(default=0)),
                ('assigned_cap', models.FloatField(default=0)),
                ('accept_cap', models.FloatField(default=0)),
                ('salary', models.IntegerField(default=0)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Forum_name', to='users.Forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Forum_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
